require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-permissions/scripts/setup'

# $RNAdMobAsStaticFramework = true
# use_frameworks! :linkage => :static

platform :ios, '11.0'

target 'BrownceCustomer' do
  config = use_native_modules!
  # $RNGoogleMobileAdsAsStaticFramework = true
  use_react_native!(:path => config["reactNativePath"])
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'Braintree', '~> 4.35.0'
  pod 'RNPaypal', :path => '../node_modules/react-native-paypal'
  pod 'Braintree/DataCollector'
  pod 'Google-Mobile-Ads-SDK'
  # pod 'OneSignalXCFramework', '>= 3.0', '< 4.0'
  setup_permissions([
    'AppTrackingTransparency'
  ])

  target 'BrownceCustomerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end

  # post_install do |installer|
  #   installer.pods_project.build_configurations.each do |config|
  #     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  #     end
  #   end

end

target 'BrownceCustomer-tvOS' do
  # Pods for BrownceCustomer-tvOS

  target 'BrownceCustomer-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

target 'OneSignalNotificationServiceExtension' do
  pod 'OneSignalXCFramework', '>= 3.0', '< 5.0'
end
