export const interBold = 'Inter-Bold'
export const interBoldItalic = 'Inter-BoldItalic'
export const interItalic = 'Inter-Italic'
export const interMedium = 'Inter-Medium'
export const interMediumItalic = 'Inter-MediumItalic'
export const inter = 'Inter-Regular'
export const interSemiBold = 'Inter-SemiBold'
export const interSemiBoldItalic = 'Inter-SemiBoldItalic'