export const LOADER = 'LOADER'
export const SEARCHLOADER = 'SEARCHLOADER'

export const POPUP = "POPUP"
export const LANGUAGE = 'LANGUAGE'
export const LOGOUT_ACTION = 'LOGOUT_ACTION'
export const MODAL_ACTION = 'MODAL_ACTION'
export const REFRESH_DATA_ACTION = 'REFRESH_DATA_ACTION'

export const REGISTRATION_ACTION = 'REGISTRATION_ACTION'
export const OTP_VIEW_ACTION = 'OTP_VIEW_ACTION'
export const OTP_VERIFICATION_ACTION = 'OTP_VERIFICATION_ACTION'
export const PROFILE_SETUP_ONE_ACTION = 'PROFILE_SETUP_ONE_ACTION'
export const PROFILE_SETUP_TWO_ACTION = 'PROFILE_SETUP_TWO_ACTION'

export const GET_COUNTRY_LIST_ACTION = 'GET_COUNTRY_LIST_ACTION'
export const GET_COUNTRY_LIST_SUCCESS_ACTION = 'GET_COUNTRY_LIST_SUCCESS_ACTION'

export const GET_STATE_LIST_BY_COUNTRY_ACTION = 'GET_STATE_LIST_BY_COUNTRY_ACTION'
export const GET_STATE_LIST_BY_COUNTRY_SUCCESS_ACTION = 'GET_STATE_LIST_BY_COUNTRY_SUCCESS_ACTION'

export const GET_CITY_LIST_BY_STATE_ACTION = 'GET_CITY_LIST_BY_STATE_ACTION'
export const GET_CITY_LIST_BY_STATE_SUCCESS_ACTION = 'GET_CITY_LIST_BY_STATE_SUCCESS_ACTION'

export const SAVE_LOCATION_ACTION = 'SAVE_LOCATION_ACTION'

export const GET_HAIR_TYPES_ACTION = 'GET_HAIR_TYPES_ACTION'
export const GET_HAIR_TYPES_SUCCESS_ACTION = 'GET_HAIR_TYPES_SUCCESS_ACTION'
export const UPDATE_HAIR_TYPES_ACTION = 'UPDATE_HAIR_TYPES_ACTION'
export const SAVE_HAIR_TYPE_ACTION = 'SAVE_HAIR_TYPE_ACTION'

export const SAVE_GENDER_ACTION = 'SAVE_GENDER_ACTION'

export const GET_PROFILE_QUESTIONS_ACTION = 'GET_PROFILE_QUESTIONS_ACTION'
export const GET_PROFILE_QUESTIONS_SUCCESS_ACTION = 'GET_PROFILE_QUESTIONS_SUCCESS_ACTION'
export const UPDATE_PROFILE_QIUESTION_ACTION = 'UPDATE_PROFILE_QIUESTION_ACTION'

export const PROFILE_QUESTION_ANSWER_LIST = 'PROFILE_QUESTION_ANSWER_LIST'
export const UPDATE_PROFILE_QUESTION_ANSWER_LIST = 'UPDATE_PROFILE_QUESTION_ANSWER_LIST'

export const SAVE_QUESTION_ANSWER_ACTION = 'SAVE_QUESTION_ANSWER_ACTION'

export const LOGIN_ACTION = 'LOGIN_ACTION'
export const FORGOT_PASSWORD_ACTION = 'FORGOT_PASSWORD_ACTION'

export const GET_PROFILE_ACTION = 'GET_PROFILE_ACTION'
export const GET_PROFILE_SUCCESS_ACTION = 'GET_PROFILE_SUCCESS_ACTION'

export const GET_OTHER_PROFILE_DETAIL_SUCCESS_ACTION = 'GET_OTHER_PROFILE_DETAIL_SUCCESS_ACTION'

export const GET_PROVIDER_PROFILE_ACTION = 'GET_PROVIDER_PROFILE_ACTION'
export const GET_PROVIDER_PROFILE_SUCCESS_ACTION = 'GET_PROVIDER_PROFILE_SUCCESS_ACTION'


export const SAVE_PROFILE_ACTION = 'SAVE_PROFILE_ACTION'
export const SAVE_PROVIDER_PROFILE_ACTION = 'SAVE_PROVIDER_PROFILE_ACTION'

export const UPDATE_PORTFOLIO = 'UPDATE_PORTFOLIO'

export const DELETE_PORTFOLIO = 'DELETE_PORTFOLIO'


export const UPDATE_MY_QUESTION_ANSWER = 'UPDATE_MY_QUESTION_ANSWER'
export const SAVE_CONTACT_DETAIL_ACTION = 'SAVE_CONTACT_DETAIL_ACTION'
export const SAVE_DEPOSIT_FEES_ACTION = 'SAVE_DEPOSIT_FEES_ACTION'
export const GET_ALL_SERVIES_ACTION = 'GET_ALL_SERVIES_ACTION'
export const GET_ALL_SERVIES_SUCCESS_ACTION = 'GET_ALL_SERVIES_SUCCESS_ACTION'

export const UPDATE_PROFILE_SETUP_SERVICES_ACTION = 'UPDATE_PROFILE_SETUP_SERVICES_ACTION'

export const UPDATE_SERVICES_ACTION = 'UPDATE_SERVICES_ACTION'

export const UPDATE_MAINTAINANCE_ACTION = 'UPDATE_MAINTAINANCE_ACTION'

export const UPDATE_PRICE_RANGE_ACTION = 'UPDATE_PRICE_RANGE_ACTION'


export const SAVE_SERVICE_ACTION = 'SAVE_SERVICE_ACTION'

export const CHANGE_SERVICE_ACTION = 'CHANGE_SERVICE_ACTION'

export const GET_SUBSCRIPTION_PLAN_ACTION = 'GET_SUBSCRIPTION_PLAN_ACTION'
export const GET_SUBSCRIPTION_PLAN_SUCCESS_ACTION = 'GET_SUBSCRIPTION_PLAN_SUCCESS_ACTION'

export const SAVE_SUBSCRIPTION_ACTION = 'SAVE_SUBSCRIPTION_ACTION'
export const UPDATE_SUBSCRIPTION_ACTION = 'UPDATE_SUBSCRIPTION_ACTION'

export const GET_SAVES_SERVICES_ACTION = 'GET_SAVES_SERVICES_ACTION'
export const GET_SAVES_SERVICES_SUCCESS_ACTION = 'GET_SAVES_SERVICES_SUCCESS_ACTION'
export const UPDATE_SAVED_SERVICES_ACTION = 'UPDATE_SAVED_SERVICES_ACTION'

export const SAVE_SERVICES_PRICE_ACTION = 'SAVE_SERVICES_PRICE_ACTION'

export const SAVE_EDIT_SERVICES_PRICE_ACTION = 'SAVE_EDIT_SERVICES_PRICE_ACTION'

export const GET_PROVIDER_LIST_ACTION = 'GET_PROVIDER_LIST_ACTION'
export const GET_PROVIDER_LIST_SUCCESS_ACTION = 'GET_PROVIDER_LIST_SUCCESS_ACTION'

export const GET_PROVIDER_DETAILS = "GET_PROVIDER_DETAILS";
export const GET_PROVIDER_DETAILS_SUCCESS = "GET_PROVIDER_DETAILS_SUCCESS";
export const GET_PROVIDER_DETAILS_FAILURE = "GET_PROVIDER_DETAILS_FAILURE";

export const GET_COMPLETE_PROVIDER_DETAIL_ACTION = 'GET_COMPLETE_PROVIDER_DETAIL_ACTION'
export const GET_COMPLETE_PROVIDER_DETAIL_SUCCESS_ACTION = 'GET_COMPLETE_PROVIDER_DETAIL_SUCCESS_ACTION'

export const GET_COMPLETE_PROVIDER_SERVICES = 'GET_COMPLETE_PROVIDER_SERVICES'
export const GET_COMPLETE_PROVIDER_PRODUCTS = 'GET_COMPLETE_PROVIDER_PRODUCTS'

export const SAVE_BOOKING_ACTION = "SAVE_BOOKING_ACTION"

export const GET_SUPPORT_INFO_ACTION = "GET_SUPPORT_INFO_ACTION"
export const GET_SUPPORT_INFO_SUCCESS_ACTION = "GET_SUPPORT_INFO_SUCCESS_ACTION"

export const GET_CUSTOMER_APPOINTMENTS_ACTION = "GET_CUSTOMER_APPOINTMENTS_ACTION"

export const GET_CUSTOMER_APPOINTMENTS_SUCCESS_ACTION = "GET_CUSTOMER_APPOINTMENTS_SUCCESS_ACTION"

export const GET_CUSTOMER_APPOINTMENTS_PAST_ACTION = "GET_CUSTOMER_APPOINTMENTS_PAST_ACTION"

export const GET_CUSTOMER_APPOINTMENTS_UPCOMING_ACTION = "GET_CUSTOMER_APPOINTMENTS_UPCOMING_ACTION"


export const CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT"

export const GET_ALL_QUESTION_ACTION = "GET_ALL_QUESTION_ACTION"

export const GET_ALL_QUESTION_SUCCESSTION_ACTION = "GET_ALL_QUESTION_SUCCESSTION_ACTION"

export const GET_PROVIDER_APPOINTMENT_ACTION = "GET_PROVIDER_APPOINTMENT_ACTION"

export const GET_PROVIDER_APPOINTMENT_SUCCESS_ACTION = "GET_PROVIDER_APPOINTMENT_SUCCESS_ACTION"

export const GET_PROVIDER_APPOINTMENT_INPROGRESS_ACTION = "GET_PROVIDER_APPOINTMENT_INPROGRESS_ACTION"

export const GET_PROVIDER_APPOINTMENT_UPCOMING_ACTION = "GET_PROVIDER_APPOINTMENT_UPCOMING_ACTION"


export const GET_PROVIDER_AVAILAIBILITY_ACTION = "GET_PROVIDER_AVAILAIBILITY_ACTION"

export const SAVE_UPLOAD_LICENSE = "SAVE_UPLOAD_LICENSE"

export const APPROVE_REJECT_APPOINTMENT_ACTION = "APPROVE_REJECT_APPOINTMENT_ACTION"

export const GET_SEARCH_SERVICES_ACTION = "GET_SEARCH_SERVICES_ACTION"

export const GET_SEARCH_SERVICES_SUCCESS_ACTION = "GET_SEARCH_SERVICES_SUCCESS_ACTION"

export const GET_SEARCH_MAINTAINANCE_SUCCESS_ACTION = "GET_SEARCH_MAINTAINANCE_SUCCESS_ACTION"


export const GET_PRICE_RANGE_ACTION = "GET_PRICE_RANGE_ACTION"

export const GET_PRICE_RANGE_SUCCESS_ACTION = "GET_PRICE_RANGE_SUCCESS_ACTION"

export const SAVE_SEARCH_PROVIDER_ACTION = "SAVE_SEARCH_PROVIDER_ACTION"

export const SAVE_SEARCH_PROVIDER_SUCCESS_ACTION = "SAVE_SEARCH_PROVIDER_SUCCESS_ACTION"

export const ADD_QUESTION_ACTION = "ADD_QUESTION_ACTION"

export const DELETE_QUESTION_ACTION = "DELETE_QUESTION_ACTION"

export const DELETE_QUESTION_SUCCESS_ACTION = "DELETE_QUESTION_SUCCESS_ACTION"

export const LIKE_DISLIKE_QUESTION_ACTION = 'LIKE_DISLIKE_QUESTION_ACTION'

export const LIKE_DISLIKE_COMMENT_ACTION = 'LIKE_DISLIKE_COMMENT_ACTION'

export const LIKE_DISLIKE_QUESTION_SUCCESS_ACTION = 'LIKE_DISLIKE_QUESTION_SUCCESS_ACTION'

export const GET_COMMON_QUESTION_ACTION = "GET_COMMON_QUESTION_ACTION"

export const GET_COMMON_QUESTION_SUCCESS_ACTION = "GET_COMMON_QUESTION_SUCCESS_ACTION"

export const MARK_APPOINTMENT_COMPLETE_ACTION = "MARK_APPOINTMENT_COMPLETE_ACTION"

export const GET_HISTORY_APPOINTMENT_ACTION = "GET_HISTORY_APPOINTMENT_ACTION"

export const GET_HISTORY_APPOINTMENT_SUCCESS_ACTION = "GET_HISTORY_APPOINTMENT_SUCCESS_ACTION"

export const CHAT_ROOM_ACTION = "CHAT_ROOM_ACTION"

export const CHAT_ROOM_SUCCESS_ACTION = "CHAT_ROOM_SUCCESS_ACTION"

export const PROVIDER_BIO_ACTION = "PROVIDER_BIO_ACTION"

export const SP_DATA_STEP_ACTION = "SP_DATA_STEP_ACTION"

export const SP_DATA_STEP_SUCCESS_ACTION = "SP_DATA_STEP_SUCCESS_ACTION"

export const CS_DATA_STEP_ACTION = "CS_DATA_STEP_ACTION"

export const CS_DATA_STEP_SUCCESS_ACTION = "CS_DATA_STEP_SUCCESS_ACTION"

export const SAVE_CHAT_ACTION = "SAVE_CHAT_ACTION"

export const GET_CHAT_MESSAGE_ACTION = "GET_CHAT_MESSAGE_ACTION"

export const GET_CHAT_MESSAGE_SUCCESS_ACTION = "GET_CHAT_MESSAGE_SUCCESS_ACTION"

export const UPDATE_CHAT_MESSAGE_HISTORY_ACTION = 'UPDATE_CHAT_MESSAGE_HISTORY_ACTION'

export const GET_CHAT_LIST_ACTION = "GET_CHAT_LIST_ACTION"

export const GET_CHAT_LIST_SUCCESS_ACTION = "GET_CHAT_LIST_SUCCESS_ACTION"

export const CLEAR_MSG_CASE = 'CLEAR_MSG_CASE'

export const COMMENT_ACTION = "COMMENT_ACTION"

export const APPOINTMENT_DETAIL_ACTION = "APPOINTMENT_DETAIL_ACTION"

export const APPOINTMENT_DETAIL_SUCCESS_ACTION = "APPOINTMENT_DETAIL_SUCCESS_ACTION"

export const START_SERVICE_ACTION = "START_SERVICE_ACTION"

export const GET_RATING_TYPES_ACTION = "GET_RATING_TYPES_ACTION"

export const GET_RATING_TYPES_SUCCESS_ACTION = "GET_RATING_TYPES_SUCCESS_ACTION"

export const SAVE_RATING_ACTION = "SAVE_RATING_ACTION"

export const SAVE_RATING_SUCCESS_ACTION = "SAVE_RATING_SUCCESS_ACTION"


export const GET_COMMENTS_HISTORY_ACTION = "GET_COMMENTS_HISTORY_ACTION"

export const GET_COMMENTS_HISTORY_SUCCESS_ACTION = "GET_COMMENTS_HISTORY_SUCCESS_ACTION"

export const UPDATE_COMMENTS_HISTORY_ACTION = "UPDATE_COMMENTS_HISTORY_ACTION"

export const GET_MY_FUNDS_ACTION = "GET_MY_FUNDS_ACTION"

export const GET_MY_FUNDS_SUCCESS_ACTION = "GET_MY_FUNDS_SUCCESS_ACTION"

export const MAKE_PAYMENT_ACTION = "MAKE_PAYMENT_ACTION"

export const MAKE_PAYMENT_SUCCESS_ACTION = "MAKE_PAYMENT_SUCCESS_ACTION"

export const GET_EARNINGS_ACTION = "GET_EARNINGS_ACTION"

export const GET_EARNINGS_SUCCESS_ACTION = "GET_EARNINGS_SUCCESS_ACTION"

export const REQUEST_FUNDS_ACTION = "REQUEST_FUNDS_ACTION"

export const REQUEST_FUND_SUCCESS_ACTION = "REQUEST_FUND_SUCCESS_ACTION"

export const RESET_PASSWORD_ACTION = "RESET_PASSWORD_ACTION"

export const CHANGE_PASSWORD_ACTION = "CHANGE_PASSWORD_ACTION"


export const GET_FUNDS_LIST_ACTION = "GET_FUNDS_LIST_ACTION"

export const GET_FUNDS_LIST_SUCCESS_ACTION = "GET_FUNDS_LIST_SUCCESS_ACTION"

export const MARK_NOTIFICATION_AS_READ_ACTION = "MARK_NOTIFICATION_AS_READ_ACTION"

export const GET_CMS_ACTION = "GET_CMS_ACTION"

export const GET_CMS_SUCCESS_ACTION = "GET_CMS_SUCCESS_ACTION"

export const CANCEL_SUBSCRIPTION_ACTION = "CANCEL_SUBSCRIPTION_ACTION"

export const CANCEL_SUBSCRIPTION_SUCCESS_ACTION = "CANCEL_SUBSCRIPTION_SUCCESS_ACTION"

export const GET_CUSTOMER_DETAIL_ACTION = "GET_CUSTOMER_DETAIL_ACTION"

export const GET_CUSTOMER_DETAIL_SUCCESS_ACTION = "GET_CUSTOMER_DETAIL_SUCCESS_ACTION"

export const GET_SP_DETAIL_ACTION = "GET_SP_DETAIL_ACTION"

export const GET_SP_DETAIL_SUCCESS_ACTION = "GET_SP_DETAIL_SUCCESS_ACTION"

export const UPDATE_EMAIL_ACTION = "UPDATE_EMAIL_ACTION"

export const VALIDATE_EMAIL_OTP_ACTION = "VALIDATE_EMAIL_OTP_ACTION"

export const UPDATE_TENDER_HEAD_LEVEL_ACTION = "UPDATE_TENDER_HEAD_LEVEL_ACTION"

export const GET_CUSTOM_SERVICES_ACTION = "GET_CUSTOM_SERVICES_ACTION"

export const GET_CUSTOM_SERVICES_SUCCESS_ACTION = "GET_CUSTOM_SERVICES_SUCCESS_ACTION"

export const ADD_CUSTOM_SERVICE_ACTION = "ADD_CUSTOM_SERVICE_ACTION"

export const UPDATE_CUSTOM_SERVICES_ACTION = "UPDATE_CUSTOM_SERVICES_ACTION"

export const UPDATE_PROFILE_SETUP_CUSTOM_SERVICES_ACTION = "UPDATE_PROFILE_SETUP_CUSTOM_SERVICES_ACTION"

export const GET_SP_CUSTOM_SERVICES_ACTION = "GET_SP_CUSTOM_SERVICES_ACTION"

export const GET_SP_CUSTOM_SERVICES_SUCCESS_ACTION = "GET_SP_CUSTOM_SERVICES_SUCCESS_ACTION"

export const FIRST_TIME_ACTION = "FIRST_TIME_ACTION"

export const ADD_PRODUCT_ACTION = "ADD_PRODUCT_ACTION"

export const GET_BRAND_CATEGORY_ACTION = "GET_BRAND_CATEGORY_ACTION"

export const GET_BRAND_SUCCESS_ACTION = "GET_BRAND_SUCCESS_ACTION"

export const GET_CATEGORY_SUCCESS_ACTION = "GET_CATEGORY_SUCCESS_ACTION"

export const GET_MY_PRODUCT_LIST_ACTION = "GET_MY_PRODUCT_LIST_ACTION"

export const GET_MY_PRODUCT_LIST_SUCCESS_ACTION = "GET_MY_PRODUCT_LIST_SUCCESS_ACTION"

export const DELETE_PRODUCT_ACTION = "DELETE_PRODUCT_ACTION"

export const DELETE_PRODUCT_SUCCESS_ACTION = "DELETE_PRODUCT_SUCCESS_ACTION"

export const CUSTOMER_PRODUCTS_ACTION = "CUSTOMER_PRODUCTS_ACTION"

export const CUSTOMER_PRODUCTS_SUCCESS_ACTION = "CUSTOMER_PRODUCTS_SUCCESS_ACTION"

export const GET_CATEGORY_SEARCH_ACTION = "GET_CATEGORY_SEARCH_ACTION"

export const GET_BRAND_SEARCH_ACTION = "GET_BRAND_SEARCH_ACTION"

export const ADD_ORDER_ACTION = "ADD_ORDER_ACTION"
export const ADD_ORDER_SUCCESS_ACTION = "ADD_ORDER_SUCCESS_ACTION"

export const MY_ADDRESS_ACTION = "MY_ADDRESS_ACTION"
export const MY_ADDRESS_SUCCESS_ACTION = "MY_ADDRESS_SUCCESS_ACTION"

export const CUSTOMER_ORDERS_ACTION = "CUSTOMER_ORDERS_ACTION"
export const CUSTOMER_ORDERS_SUCCESS_ACTION = "CUSTOMER_ORDERS_SUCCESS_ACTION"

export const PROVIDER_ORDERS_ACTION = "PROVIDER_ORDERS_ACTION"
export const PROVIDER_ORDERS_SUCCESS_ACTION = "PROVIDER_ORDERS_SUCCESS_ACTION"


export const PAYMENT_SAVE_ACTION = "PAYMENT_SAVE_ACTION"
export const MARK_PRODUCT_DELEVERED_ACTION = "MARK_PRODUCT_DELEVERED_ACTION"

export const CANCEL_ORDER_ACTION = "CANCEL_ORDER_ACTION"
export const CANCEL_ORDER_SUCCESS_ACTION = "CANCEL_ORDER_SUCCESS_ACTION"


export const ADD_BRAND_NAME_ACTION = "ADD_BRAND_NAME_ACTION"

export const ORDER_STATUS_ACTION = "ORDER_STATUS_ACTION"
export const ORDER_STATUS_SUCCESS_ACTION = "ORDER_STATUS_SUCCESS_ACTION"


export const OPENTIME_ACTION = "OPENTIME_ACTION"
export const ORDERTIME_SUCCESS_ACTION = "ORDERTIME_SUCCESS_ACTION"

export const DELETE_COMMENT_ACTION = 'DELETE_COMMENT_ACTION'

export const GET_SUGGESTIONS_ACTION = 'GET_SUGGESTIONS_ACTION'
export const GET_SUGGESTIONS_SUCCESS_ACTION = 'GET_SUGGESTIONS_SUCCESS_ACTION'

export const GET_NOTIFICATION_LIST_ACTION = 'GET_NOTIFICATION_LIST_ACTION'

export const GET_NOTIFICATION_COUNT_ACTION = 'GET_NOTIFICATION_COUNT_ACTION'
export const GET_NOTIFICATION_COUNT_SUCCESS_ACTION = 'GET_NOTIFICATION_COUNT_SUCCESS_ACTION'

export const GET_QUESTION_BY_ID_ACTION = "GET_QUESTION_BY_ID_ACTION"

export const GET_PROFESSIONS_LIST_ACTION = 'GET_PROFESSIONS_LIST_ACTION'
export const GET_PROFESSIONS_LIST_SUCCESS_ACTION = 'GET_PROFESSIONS_LIST_SUCCESS_ACTION'

export const UPDATE_SERVICE_PRICE_ACTION = 'UPDATE_SERVICE_PRICE_ACTION'
export const UPDATE_SERVICE_PRICE_SUCCESS_ACTION = 'UPDATE_SERVICE_PRICE_SUCCESS_ACTION'

export const GET_SERVICES_BY_PROFESSION_ACTION = 'GET_SERVICES_BY_PROFESSION_ACTION'
export const GET_SERVICES_BY_PROFESSION_SUCCESS_ACTION = 'GET_SERVICES_BY_PROFESSION_SUCCESS_ACTION'

export const ADD_PROVIDER_PROFESSION_ACTION = 'ADD_PROVIDER_PROFESSION_ACTION'
export const ADD_PROVIDER_PROFESSION_ACTION_SUCCESS = 'ADD_PROVIDER_PROFESSION_ACTION_SUCCESS'

export const DELETE_ACCOUNT_ACTION = 'DELETE_ACCOUNT_ACTION'
export const GET_FILTER_PRICE_LIST_ACTION = 'GET_FILTER_PRICE_LIST_ACTION'
export const GET_ALL_CITY_LIST_ACTION = 'GET_ALL_CITY_LIST_ACTION'

export const ADD_REMOVE_PROFILE_TO_FAVOURITE = 'ADD_REMOVE_PROFILE_TO_FAVOURITE'
export const GET_FAV_PROVIDER_LIST_ACTION = 'GET_FAV_PROVIDER_LIST_ACTION'

export const SAVE_APP_FEEDBACK_ACTION = 'SAVE_APP_FEEDBACK_ACTION'