
/**
 * Created by erichua on 13/12/2017.
 */
// data generated by http://www.richyli.com/name/index.asp
export default [
  // {'searchStr': 'Allure Beauty'},
  // {'searchStr': 'Applied Assurance'},
  // {'searchStr': 'Angle Angles'},
  // {'searchStr': 'Angle angles'},
  {'searchStr': 'Colorbar'},
  {'searchStr': 'Clinique'},
  {'searchStr': 'Cream'},

  {'searchStr': 'Beauty Basics'},
  {'searchStr': 'Bossy Beauties'},
  {'searchStr': 'Beauty Beauty'},

  
  {'searchStr': 'Dior'},
  {'searchStr': 'Dio'},

  {'searchStr': 'Envy'},
  {'searchStr': 'Fairy Cream'},
  
] 
